pipeline {
    agent { label 'mac-mini-slave' }

    environment {
        LC_ALL = 'en_US.UTF-8'
        APP_NAME = 'PagoCoreSDK'
        BUILD_NAME = 'PagoCoreSDK'
        APP_TARGET = 'PagoCoreSDK'
        APP_PROJECT = 'PagoCoreSDK.xcodeproj'
        APP_WORKSPACE = 'PagoCoreSDK.xcworkspace'
        APP_TEST_SCHEME = 'PagoCoreSDK'
        PUBLISH_TO_CHANNEL = 'slack'
    }

    stages {
        stage('Unit Test cases') {
            steps {
                script {
                    try {
                        sh "fastlane tests"
                    } catch(exc) {
                        currentBuild.result = "UNSTABLE"
                        error('There are failed tests.')
                    }
                }
            }

        }
    }

}
